# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apiclient:
    container_name: apiclient
    image: apiclient
    build:
      context: .
      dockerfile: ApiClient/Dockerfile
    ports:
      - 5289:5289
    depends_on:
      - database

  database:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1StrongPassword
      - MSSQL_PID=Developer
  
  json-server:
    build: node:21-alpine
    ports:
      - 4000:4000
    command: >
      - npm install -g json-server
      - npm run server
      - json-server --watch ./db/dados.json --port 4000 --host 0.0.0.0

#docker compose down
#docker compose up -d --wait --force-recreate