FROM mcr.microsoft.com/mssql/server:2022-latest
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Developer
ARG MSSQL_SA_PASSWORD=Default(0!)Password

COPY ./script.sql /scripts/script.sql
#RUN sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -i /script/script.sql 
RUN sleep 30
RUN /opt/mssql-tools/bin/sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -l 90 -e -i /scripts/script.sql



