// <auto-generated />
using ApiClient.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiClient.Services.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231125222101_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiClient.Models.SecurityModel", b =>
                {
                    b.Property<string>("ISINCode")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("isin");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("price");

                    b.HasKey("ISINCode");

                    b.ToTable("Securities", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
